language: node_js
node_js: 10.15
cache:
  yarn: true
addons:
  apt:
    packages:
      - libgconf-2-4
install:
  - yarn install --frozen-lockfile
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: heroku
  api_key:
    secure: SrAtKHURhSNFxjKGYLTiGx29WSwzzPJeO7nZWZhKbMCchim/wHbt7HU1ybQnAB+abBb+DtZmcU5PycqJiQJ7RUToVLNbbx+jPPJpY2e0W/FPpaxOANtiNWw9qAk0+5asabkZtBgjnITeK6sNGOu/CNozhkR53Vnhl7S4X1one6YibxHgCexghpNwejHVMBv1FNYak6LBc4j90T9FZok2Z258kTUdxX3YPCL7RbfkYZ7d4Gbfes1YCHukKUMscwc8xK4inIHJPjfl9pUh24JVLL2WwmSFrOl9ivf6n+CGa06J14yYYmZncAgsDGZ7heaB4scRJCablwbm8I5RXe0R14mKYPX+gc0uw41z/exsjh2B1WpBl3sT+05X7/eZch3GtNsqevLlysUiB9Fq3x4ZKNj2gEGtOVCQ/tBIg/5+6N+/0TNS0HEOHWm8WOLoHLhln+aucSIlx2yEasbXnjQWA04m/oj4sZTHTUX2wJ/5y2mfqZcA9DQ/KChUlPjbqLw5SGAPpdaEFRecgtYjFa2YpGnLM50W8xVMQn/Jx+uWZ40nuDO+mNkciHX1PnFgVmKMeOCw1j+JIid4rWTzItNl64FEI2F/IzvBBAPKJyrhIc/+nMRP3hygjrhBHtzicQeYbihWwE4xJvpr4TMS6Rg+GiyL3w0axcRnDgij2OnNOCI=
  app:
    master: portfolio1001
    production: portfolio1002
