language: node_js
node_js: 10.15
cache:
  yarn: true
addons:
  apt:
    packages:
      - libgconf-2-4
install:
  - yarn install --frozen-lockfile
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: heroku
  api_key:
    secure: QNAqva8E/C/LZUGjYT4Mug9tTxpKh7rduRs9nKApKVR7B1UK0KfCZgqFq+NlcrBlvjNVEALFNbbls4gyH9N2KvVjY272IWZWHUJmBwn6XepF5C2xZmsRhSgb3c16EOs8pSCKi7SYwUYaGbD3uQOMOcLJJ6U/OY4CUd8C1wDDDMnGQA3+8rwSm7S6yd7ajKkLD0CdhtAlQ6ZIWTQSjxdf3sgC2BCavaUFwtFLlsxaYt+3DJv32mZ9hwKqbK4c+NU5jX5iyAiYaIgZD0IflKRp4DIKMSX2a5+Y8jYrNnt6jmKp8HRn0UZ2VO/3D+fn7g+PTxVT4y4GInw/504Fb/lmOrAAVxYW/pF2Mq6LGtaHqa2tYn+x5erKDdvDxivMUfEFiEISUCu2YACwvBIGY2EEbR8TAgGxLxr7NWAcEI1AjOzXYCW392lCcLpNslW56ByQZNxidzIWi7frV8a89sDfDCdtl1moUGZpOuwJb8rYOvGzmmPrwd7jvpJQ1xJ/NJnbGS46fnkibhOu5lNwZVG10nWnPmuunXUvD3KoGp0wUmcmdkmJTjogHsx5a46Pk8813si9Rn80ZJvmcrgOpEIdkqVDgJdszf6mAD1dUQA76PjMgHDg/6mxFQyDaoCIqiDR1C6tBnq47rT5xP5zzrqYB+9ZHnIs1h+F/gcyrPRHY64=
  app: portfolio1001
